### ISSUE TITLE
Default saga type naming changed from Type.FullName to Type.Name

### ISSUE THREAD

**Issue by dietermijle** [rebus-org/Rebus.MySql#30]
We noticed an issue while upgrading from Rebus.MySql v2.2.0 to v4.0.0.

In our database, we noticed that the `saga_type` stored in the index table no longer contains the full name of the type, but only the name.

* Old behavior: Type.FullName - see https://github.com/rebus-org/Rebus.MySql/blob/2.2.0/Rebus.MySql/MySql/Sagas/MySqlSagaStorage.cs#L345
* New behavior: Type.Name - see https://github.com/rebus-org/Rebus.MySql/blob/4.0.0/Rebus.MySql/MySql/Sagas/DefaultSagaTypeNamingStrategy.cs#L13

Is this expected? Why did the default behavior change? And how can we easily override this behavior?

**Comment by dietermijle** [comment]
In meantime, we were able to overcome this issue by implementing and registering our own `ISagaTypeNamingStrategy` which uses the old implementation.

```
configurer.Register<ISagaTypeNamingStrategy>(_ => new FullSagaTypeNamingStrategy());
```

```
public class FullSagaTypeNamingStrategy : ISagaTypeNamingStrategy
{
    public string GetSagaTypeName(Type sagaDataType, int maximumLength)
    {
        return sagaDataType.FullName;
    }
}
```

So 2 questions remain:

1. Is this change in behavior expected? In other words, is it expected to use the name only as default saga type name?
2. Why did this behavior change? What are the benefits to use the name only compared to the full type name?

**Comment by mookid8000** [comment]
@dietermijle good question!

Honestly, I don't know why this particular default was changed. It _could_ be because other saga persisters use the same strategy, and so it makes the behavior more consistent across persistence options.

From an aesthetics pov I must also admit that I personally would prefer the simple names, instead of the fully qualified type names, but I totally get why that that's just my opinion. 😅 

Good to hear you made it work in the end. I'm closing this issue for now - feel free to get back in here if you believe there's an issue.

**Comment by dietermijle** [comment]
Thanks for the reply, @mookid8000!
In a distributed architecture, the same Saga name might be used in different services/applications using the same bus.
As such, the fully qualified type name suits us better.

**Comment by mookid8000** [comment]
Yeah I can definitely understand why it would make sense in (literally as well as logically) distributed architectures, and I also understand why it might feel like a bit of a nasty surprise to update, and then suddenly the default is different. 😅
